#!/usr/bin/env Rscript

#' Watch all problem solution directories and run tests when changes occur

# set our preferred CRAN repo
r <- getOption("repos")
r["CRAN"] <- "https://cran.rstudio.com"
options(repos = r)

# Create a list of required packages
required.packages <- c("testthat", "magrittr", "purrr")
# Figure out which ones are not already installed
to.install <- required.packages[!(required.packages %in% installed.packages()[, "Package"])]
# Install the missing packages if necessary
if (length(to.install)) install.packages(to.install)

# Load required packages
lapply(required.packages, require, character.only = TRUE)

# Utility function to "clear" the screen (actually prints 100 newlines)
clear <- function() system2("clear")

# Get a list of all directories to watch
watched.dirs <- list.files(pattern = "\\d{4}_.*", full.names = TRUE)

# Callback to run tests in changed directories
run.tests.on.changed <- function(added, deleted, modified) {
  # Clear the screen
  clear()
  # get the list of new or changed files
  append(added, modified) %>%
  # split the paths using the directory separator
  map(strsplit, split = "/") %>%
  # grab the folder names
  map(pluck, 1, 2) %>%
  # and run the tests using the "progress" reporter
  map(test_dir, reporter = "progress")
  # return true so that watch() won't exit
  return(TRUE)
}

# Watch all problem solution directories for changes to source code files
watch(watched.dirs, run.tests.on.changed, pattern = ".*\\.R")

# Clear the screen
clear()
